# Generated by Django 4.0.3 on 2022-03-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='img',
        ),
    ]
