# Generated by Django 4.0.3 on 2022-03-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_posts_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(default=1, upload_to='posts'),
            preserve_default=False,
        ),
    ]
