# Generated by Django 4.0.3 on 2022-03-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_posts_post_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
