# Generated by Django 4.0.1 on 2022-03-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('assunto', models.CharField(max_length=100, null=True)),
                ('mensagem', models.TextField(null=True)),
                ('email_sent', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
