# Generated by Django 4.0.1 on 2022-03-23 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_contato_data_alter_contato_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('comentario', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('Lido', 'Lido'), ('Não lido', 'Não Lido')], default='Não Lido', max_length=20)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
