# Generated by Django 4.0.1 on 2022-03-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_commentpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='creat_at',
            new_name='criado',
        ),
    ]
