# Generated by Django 4.0.4 on 2022-08-31 21:31

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('assunto', models.CharField(max_length=100, null=True)),
                ('mensagem', models.TextField(null=True)),
                ('email_sent', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('categoria', models.CharField(choices=[('Web Design', 'Web Design'), ('Web Development', 'Web Development'), ('Linguagens de Programação', 'Linguagens de Programação')], max_length=45)),
                ('img', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('comentario', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('Lido', 'Lido'), ('Não lido', 'Não Lido')], default='Não Lido', max_length=20)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.post')),
            ],
        ),
    ]
